
name: "Verify"
on: "push"

jobs:
    verify:
        runs-on: ubuntu-latest
        defaults:
            run:
               shell: bash
        steps:
        -   shell: bash
            name: "Bash Version"
            run: bash --version
    
